# -*- coding: utf-8 -*-
"""dogs_and_cats_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkZ_Lj1zT5Tsr5TxRTooN8yL9okTqe4F
"""

# Commented out IPython magic to ensure Python compatibility.
try:
  # This command only in Colab.
#   %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import os
import numpy as np
import matplotlib.pyplot as plt

# Get project files
!wget https://cdn.freecodecamp.org/project-data/cats-and-dogs/cats_and_dogs.zip

#!unzip cats_and_dogs.zip

PATH = 'cats_and_dogs'

train_dir = os.path.join(PATH, 'train')
validation_dir = os.path.join(PATH, 'validation')
test_dir = os.path.join(PATH, 'test')

# Get number of files in each directory. The train and validation directories
# each have the subdirecories "dogs" and "cats".
total_train = sum([len(files) for r, d, files in os.walk(train_dir)])
total_val = sum([len(files) for r, d, files in os.walk(validation_dir)])
total_test = len(os.listdir(test_dir))

# Variables for pre-processing and training.
batch_size = 128
epochs = 15
IMG_HEIGHT = 150
IMG_WIDTH = 150

os.makedirs('cats_and_dogs/test/dummy_class')

import shutil

for filename in os.listdir(test_dir):
  file_path=os.path.join(test_dir, filename)

  if os.path.isfile(file_path):
    shutil.move(file_path, 'cats_and_dogs/test/dummy_class')

# 3
train_image_generator = ImageDataGenerator(
    rescale=1.0/255,          # Normalize pixel values to range [0, 1]
)
validation_image_generator = ImageDataGenerator(
    rescale=1.0/255,          # Normalize pixel values to range [0, 1]
)
test_image_generator = ImageDataGenerator(
    rescale=1.0/255,          # Normalize pixel values to range [0, 1]
)

train_data_gen = train_image_generator.flow_from_directory(batch_size=batch_size,
                                                     directory=train_dir,
                                                     target_size=(IMG_HEIGHT, IMG_WIDTH),
                                                     class_mode='binary')
val_data_gen = validation_image_generator.flow_from_directory(batch_size=batch_size,
                                                     directory=validation_dir,
                                                     target_size=(IMG_HEIGHT, IMG_WIDTH),
                                                     class_mode='binary')
test_data_gen = test_image_generator.flow_from_directory(
    directory=test_dir,
    class_mode=None,  # No labels for testing
    target_size=(IMG_HEIGHT, IMG_WIDTH),  # Correct argument for resizing images
    batch_size=batch_size,
    shuffle=False
)

# 4
def plotImages(images_arr, probabilities = False):
    fig, axes = plt.subplots(len(images_arr), 1, figsize=(5,len(images_arr) * 3))
    #axes = np.atleast_1d(axes)  # Ensure axes is always iterable
    if probabilities is False:
      for img, ax in zip( images_arr, axes):
          ax.imshow(img)
          ax.axis('off')
    else:
      for img, probability, ax in zip( images_arr, probabilities, axes):
          ax.imshow(img)
          ax.axis('off')
          if probability > 0.5:
              ax.set_title("%.2f" % (probability*100) + "% dog")
          else:
              ax.set_title("%.2f" % ((1-probability)*100) + "% cat")
    plt.show()

sample_training_images, _ = next(train_data_gen)
plotImages(sample_training_images[:5])

# 5
train_image_generator =  ImageDataGenerator(
    rescale=1.0/255,          # Normalize pixel values to range [0, 1]
    rotation_range=30,        # Rotate images randomly within 30 degrees
    width_shift_range=0.2,    # Shift images horizontally by 20%
    height_shift_range=0.2,   # Shift images vertically by 20%
    shear_range=0.2,          # Apply shearing transformations
    zoom_range=0.2,           # Randomly zoom into images
    horizontal_flip=True,     # Flip images horizontally
    fill_mode='nearest'       # Fill in pixels for missing areas after transformations
)

# 6
train_data_gen = train_image_generator.flow_from_directory(batch_size=batch_size,
                                                     directory=train_dir,
                                                     target_size=(IMG_HEIGHT, IMG_WIDTH),
                                                     class_mode='binary')
#print(train_data_gen[0][0][0])
#augmented_images = [train_data_gen[0][0][0] for i in range(6)]

#plotImages(augmented_images)

augmented_images = [train_data_gen[0][0][0] for i in range(6)]

plotImages(augmented_images)

# 7
model_2 = Sequential()
model_2.add(Conv2D(16, 3, padding='same', activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH ,3)))
model_2.add(MaxPooling2D(pool_size=(2,2),strides=2, padding='same'))
model_2.add(Conv2D(32, 3, padding='same', activation='relu'))
model_2.add(MaxPooling2D(pool_size=(2,2),strides=2, padding='same'))
model_2.add(Conv2D(64, 3, padding='same', activation='relu' ))
model_2.add(MaxPooling2D(pool_size=(2,2),strides=2, padding='same'))

model_2.add(Flatten())

model_2.add(Dense(512, activation='relu'))
model_2.add(Dense(1, activation='sigmoid'))

model_2.summary()

model_2.compile(optimizer='rmsprop',loss='binary_crossentropy', metrics=['accuracy'])

history=model_2.fit(train_data_gen, steps_per_epoch=len(train_data_gen), epochs=20, validation_data=val_data_gen, validation_steps=len(val_data_gen), batch_size=256)

model_2.save('dogs_and_cats_classifier_model_2(1).keras')

# 9
# Assuming the model was trained for 5 epochs
epochs = 20
epochs_range = range(epochs)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

probabilities=model_2.predict(test_data_gen)

probabilities_1=[]
for i in probabilities:
  probabilities_1.append(i[0])

import numpy as np  # Ensure numpy is imported

answers = [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
           1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
           1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
           1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
           0, 0, 0, 0, 0, 0]

correct = 0

# Iterate through probabilities and answers
for probability, answer in zip(probabilities, answers):
    # Ensure probability is a scalar before rounding
    if round(float(probability)) == answer:  # Convert to float for rounding
        correct += 1

percentage_identified = (correct / len(answers)) * 100

passed_challenge = percentage_identified >= 63

print(f"Your model correctly identified {round(percentage_identified, 2)}% of the images of cats and dogs.")

if passed_challenge:
    print("You passed the challenge!")
else:
    print("You haven't passed yet. Your model should identify at least 63% of the images. Keep trying. You will get it!")